@startuml
left to right direction

actor ライフオーナー as lifeOwner
actor 相談依頼人 as client
actor FP as fp
actor 担当FP as assignedFp

client --|> lifeOwner
assignedFp --|> fp

package システム {
  usecase "担当FPへライフイベント表について\n閲覧・コメント・更新できる権限を付与する" as authorizeForLifeEventList
  usecase "担当FPへキャッシュフロー表について\n閲覧・コメント・更新できる権限を付与する" as authorizeForCashFlowList
  usecase "担当FPへ個人バランスシートについて\n閲覧・コメント・更新できる権限を付与する" as authorizeForPersonalBalanceSheet
  usecase "担当FPへメッセージや画像を送る" as sendMessageForAssingedFp
  usecase "プロジェクトにアサインするFPを募集・決定する" as proposalForProject

  usecase "プロジェクトを作成・削除する" as operateProject
  usecase "プロジェクトに紐づく\nライフプランを作成・削除をする" as operateLifePlan
  usecase "ライフプランにひもづく\nライフイベント表を作成・更新・削除をする" as operateLifeEventList
  usecase "ライフプランにひもづく\nキャッシュフロー表を作成・更新・削除をする" as operateCashFlowList
  usecase "ライフプランにひもづく\n個人バランスシートを作成・更新・削除をする" as operatePersonalBalanceSheet

  usecase "相談依頼人が許可した場合に限り\nライフイベント表を閲覧・コメント・更新する" as operateLimitedlyForLifeEventList
  usecase "相談依頼人が許可した場合に限り\nキャッシュフロー表を閲覧・コメント・更新する" as operateLimitedlyForCashFlowList
  usecase "相談依頼人が許可した場合に限り\n個人バランスシートを閲覧・コメント・更新する" as operateLimitedlyForPersonalBalanceSheet
  usecase "相談依頼人メッセージや画像を送る" as sendMessageForClient

  usecase "募集しているプロジェクトから担当FPへの応募をする" as requestProposalForProject
  usecase "持っている資格や経歴を書く" as writeLicenseAndCareer
}
client --> authorizeForLifeEventList
client --> authorizeForCashFlowList
client --> authorizeForPersonalBalanceSheet
client --> sendMessageForAssingedFp
client --> proposalForProject

operateLimitedlyForLifeEventList <-- assignedFp
operateLimitedlyForCashFlowList <-- assignedFp
operateLimitedlyForPersonalBalanceSheet <-- assignedFp
sendMessageForClient <-- assignedFp

lifeOwner --> operateProject
lifeOwner --> operateLifePlan
lifeOwner --> operateLifeEventList
lifeOwner --> operateCashFlowList
lifeOwner --> operatePersonalBalanceSheet

requestProposalForProject <-- fp
writeLicenseAndCareer <-- fp
@enduml